A manuals.playstation.net 192.168.1.25
#Redirect
A ^the\.gate 192.168.1.25
A ^www\.playstation\.com 192.168.1.25
A ^manuals\.playstation\.net 192.168.1.25
A ^(get|post)\.net\.playstation\.net 192.168.1.25
A ^(d|f|h)[a-z]{2}01\.(ps5|ps4|psp2|psv)\.update\.playstation\.net 192.168.1.25
A ^update\.playstation\.net 192.168.1.25
A ^ecode\.np\.cs\.playstation\.net 192.168.1.25
A ^ctest\.cdn\.nintendo\.net 192.168.1.25

#Block
A ^(.*\.)?207\.net 0.0.0.0
A ^(.*\.)?akadns\.net 0.0.0.0
A ^(.*\.)?akamai\.net 0.0.0.0
A ^(.*\.)?akamaiedge\.net 0.0.0.0
A ^(.*\.)?cddbp\.net 0.0.0.0
A ^(.*\.)?ea\.com 0.0.0.0
A ^(.*\.)?edgekey\.net 0.0.0.0
A ^(.*\.)?edgesuite\.net 0.0.0.0
A ^(.*\.)?llnwd\.net 0.0.0.0
A ^(.*\.)?playstation\.(com|net|org) 0.0.0.0
A ^(.*\.)?ribob01\.net 0.0.0.0
A ^(.*\.)?sbdnpd\.com 0.0.0.0
A ^(.*\.)?scea\.com 0.0.0.0
A ^(.*\.)?sonyentertainmentnetwork\.com 0.0.0.0
A ^(.*\.)?nintendo\.net 0.0.0.0
